### PR TITLE
Create README.md for product analytics instructions

### PR DESCRIPTION
**Pull request by okane16**

### CODE REVIEW

**Review by 03cranec — COMMENTED** [review]
Content looks good. My only concern is that when we start to duplicate documentation in different places, it gets really easy to forget to update all the places when things change. 

Given this is in the same repo as our docs, maybe there is a way to reference/pull the reference file from the docs to here? I think @callicles did something like this for another readme?

**Comment by callicles** [comment]
Where is that duplicated from?

**Comment by okane16** [comment]
> Where is that duplicated from?

RIght now its not duplicated from anywhere. It could be duplicated by the template detail page content on moosejs.com/templates/[template id] but currently that page does not use markdown

**Comment by callicles** [comment]
Let's merge then

**Review by callicles — APPROVED** [review]

**Pull request merged**
