### PR TITLE
rotate log per day

### PR DESCRIPTION
**Pull request by phiSgr**

### CODE REVIEW

**Comment by callicles** [comment]
Should we add something for deleting logs files that are too old?

**Comment by phiSgr** [comment]
fern doesn't have that out of the box

**Comment by phiSgr** [comment]
but the user can specify a date pattern that updates once a month

**Comment by callicles** [comment]
? what do you mean we know where it should be and it is in a dedicated `.moose` directory

**Review by callicles — APPROVED** [review]
thx!

**Pull request merged**
